x-healthcheck: &healthcheck
  test: [ "CMD", "curl", "-sf", "http://localhost:${RPC_PORT}" ]
  interval: 5s
  timeout: 5s
  retries: 3
  start_period: 30s

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  l2-geth:
    restart: "unless-stopped"
    build:
      context: .
      dockerfile: Dockerfile.binary
      args:
        - DOCKER_TAG=${L2GETH_DOCKER_TAG}
    image: l2-geth:mantle
    pull_policy: build
    stop_grace_period: 5m
    volumes:
      - mantle-data:/var/lib/op-geth
    environment:
      ETH1_HTTP: ${L1_RPC}
      SEQUENCER_CLIENT_HTTP: ${SEQUENCER}
      ROLLUP_STATE_DUMP_PATH: ${GENESIS}
      ROLLUP_CLIENT_HTTP: ${DTL}
      ROLLUP_BACKEND: 'l2'
      #ETH1_CTC_DEPLOYMENT_HEIGHT: 8
      RETRIES: 60
      ROLLUP_VERIFIER_ENABLE: 'true'
      LOG_LEVEL: ${LOG_LEVEL}
      BLOCK_SIGNER_KEY: 9f50ccaebd966113a0ef09793f8a3288cd0bb2c05d20caa3c0015b4e665f1b2d
      BLOCK_SIGNER_ADDRESS: 0x000000b36A00872bAF079426e012Cf5Cd2A74E8b
      ROLLUP_TIMESTAMP_REFRESH: 5s
      ETH1_CTC_DEPLOYMENT_HEIGHT: "17577586"
      ROLLUP_ENFORCE_FEES: 'true'
      ROLLUP_FEE_THRESHOLD_DOWN: "1"
      ROLLUP_FEE_THRESHOLD_UP: "4000"
      GASPRICE: "0"
      ETH1_SYNC_SERVICE_ENABLE: 'true'
      ETH1_CONFIRMATION_DEPTH: "0"
      ROLLUP_POLL_INTERVAL_FLAG: 500ms
      ROLLUP_ENABLE_L2_GAS_POLLING: 'true'
      RPC_ENABLE: 'true'
      RPC_ADDR: 0.0.0.0
      RPC_PORT: "${RPC_PORT}"
      RPC_API: eth,net,rollup,web3
      RPC_CORS_DOMAIN: '*'
      RPC_VHOSTS: '*'
      WS: 'true'
      WS_ADDR: '0.0.0.0'
      WS_PORT: "${WS_PORT}"
      WS_API: eth,net,rollup,web3
      WS_ORIGINS: '*'
      CHAIN_ID: "5000"
      GCMODE: full
      IPC_DISABLE: 'true'
      NETWORK_ID: "5000"
      NO_USB: 'true'
      NO_DISCOVER: 'true'
      TARGET_GAS_LIMIT: "30000000"
      USING_BVM: 'true'
      SNAPSHOT: ${SNAPSHOT:-}
      EL_EXTRAS: ${EL_EXTRAS:-}
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - geth
      - --datadir
      - /var/lib/op-geth
      - --password
      - /var/lib/op-geth/password
      - --allow-insecure-unlock
      - --unlock
      - 0x000000b36A00872bAF079426e012Cf5Cd2A74E8b
      - --mine
      - --miner.etherbase
      - 0x000000b36A00872bAF079426e012Cf5Cd2A74E8b
      - --metrics
      - --metrics.expensive
      - --pprof
      - --pprofaddr
      - 0.0.0.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.${RPC_HOST:-mantle}.service=${RPC_HOST:-mantle}
      - traefik.http.routers.${RPC_HOST:-mantle}.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-mantle}.rule=Host(`${RPC_HOST:-mantle}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-mantle}.tls.certresolver=letsencrypt
      - traefik.http.routers.${RPC_HOST:-mantle}lb.service=${RPC_HOST:-mantle}
      - traefik.http.routers.${RPC_HOST:-mantle}lb.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-mantle}lb.rule=Host(`${RPC_LB:-mantle-lb}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-mantle}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${RPC_HOST:-mantle}.loadbalancer.server.port=${RPC_PORT:-8545}
      - traefik.http.routers.${WS_HOST:-mantlews}.service=${WS_HOST:-mantlews}
      - traefik.http.routers.${WS_HOST:-mantlews}.entrypoints=websecure
      - traefik.http.routers.${WS_HOST:-mantlews}.rule=Host(`${WS_HOST:-mantlews}.${DOMAIN}`)
      - traefik.http.routers.${WS_HOST:-mantlews}.tls.certresolver=letsencrypt
      - traefik.http.routers.${WS_HOST:-mantlews}lb.service=${WS_HOST:-mantlews}
      - traefik.http.routers.${WS_HOST:-mantlews}lb.entrypoints=websecure
      - traefik.http.routers.${WS_HOST:-mantlews}lb.rule=Host(`${WS_LB:-mantlews-lb}.${DOMAIN}`)
      - traefik.http.routers.${WS_HOST:-mantlews}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${WS_HOST:-mantlews}.loadbalancer.server.port=${WS_PORT:-8546}
      - metrics.scrape=true
      - metrics.path=/debug/metrics/prometheus
      - metrics.port=6060

  set-prune-marker:
    profiles: ["tools"]
    image: alpine:3
    restart: "no"
    volumes:
      - mantle-data:/var/lib/op-geth
    entrypoint: ["/bin/sh","-c"]
    command: /bin/sh

volumes:
  mantle-data:
