ARG DOCKER_TAG=v1.0.1

FROM mantlenetworkio/op-node:${DOCKER_TAG}

RUN apk update && apk add --no-cache ca-certificates tzdata bash su-exec curl

RUN mkdir -p /var/lib/op-node/ee-secret

# Cannot assume buildkit, hence no chmod
COPY ./docker-entrypoint.sh /usr/local/bin/
# Belt and suspenders
RUN chmod -R 755 /usr/local/bin/*

ENTRYPOINT ["op-node"]
